# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-8.2"
  config.vm.synced_folder "../..", "/home/vagrant/apk-editor-studio"
  config.vm.provider "virtualbox" do |v|
    v.name = "APK Editor Studio (Debian 8.2)"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y qt5-default libsecret-1-dev dh-make devscripts
  SHELL
end
